export interface IndustryConfig {
  label: string;
  audiences: string[];
  competitors: string[];
  painPoints: string[];
  readingSuggestions: Array<{ title: string; author: string; type: string }>;
  channelPriorities: string[];
  strategicThemes: string[];
  categoryTension: string;
}

export const INDUSTRY_CONFIG: Record<string, IndustryConfig> = {
  hospitality: {
    label: "Hospitality & Food",
    audiences: [
      "Local Dining Regulars",
      "Travel & Tourism Visitors",
      "Corporate & Group Bookings",
      "Food Media & Critics",
      "Delivery & Online Platform Users",
      "Loyalty & Returning Guests",
      "Private Event Clients",
      "Lifestyle Influencers",
    ],
    competitors: [
      "Nobu Restaurants",
      "The Ivy Collection",
      "Soho House",
      "Noma / Nordic model",
      "Ottolenghi",
      "Local independents",
      "Delivery-first brands",
      "Hotel F&B concepts",
    ],
    painPoints: [
      "Seasonal demand volatility and revenue inconsistency",
      "High staff turnover undermining brand consistency",
      "Commoditisation by aggregator platforms eroding margin",
      "Difficulty conveying quality and atmosphere digitally",
      "Competing on price rather than on experience",
    ],
    readingSuggestions: [
      { title: "Setting the Table", author: "Danny Meyer", type: "Book" },
      { title: "Unreasonable Hospitality", author: "Will Guidara", type: "Book" },
      { title: "Eater", author: "Eater.com", type: "Publication" },
      { title: "Food & Wine", author: "Food & Wine Media", type: "Magazine" },
    ],
    channelPriorities: [
      "Social Media (Organic)",
      "Influencer",
      "PR & Media Relations",
      "Experiential / Events",
    ],
    strategicThemes: [
      "Experience over product",
      "Loyalty through culture",
      "Story as the menu",
    ],
    categoryTension: "Authenticity vs. scale — keeping soul as you grow",
  },
  architecture: {
    label: "Architecture & Design",
    audiences: [
      "Private Residential Clients (HNW)",
      "Property Developers",
      "Commercial Real Estate Commissioners",
      "Public Sector Clients",
      "Design & Architecture Media",
      "Planning Authorities",
      "Interior Design Partners",
      "International Investors",
    ],
    competitors: [
      "Zaha Hadid Architects",
      "Foster + Partners",
      "Snøhetta",
      "Adjaye Associates",
      "Local design studios",
      "Developer-aligned practices",
      "Value-engineering firms",
    ],
    painPoints: [
      "Long sales cycles with unpredictable conversion",
      "Portfolio-driven reputation without strategic narrative",
      "Difficulty differentiating from visually similar practices",
      "Reliance on word-of-mouth with no earned media strategy",
      "Fee pressure from procurement-led processes",
    ],
    readingSuggestions: [
      { title: "Dezeen", author: "Dezeen Media", type: "Publication" },
      { title: "Architectural Digest", author: "Condé Nast", type: "Magazine" },
      { title: "The Architecture of Happiness", author: "Alain de Botton", type: "Book" },
      { title: "Wallpaper*", author: "Wallpaper Media", type: "Magazine" },
    ],
    channelPriorities: [
      "PR & Media Relations",
      "Content Marketing",
      "Social Media (Organic)",
      "OOH / Print",
    ],
    strategicThemes: [
      "Authority through ideas",
      "Craft as brand equity",
      "Clients as collaborators",
    ],
    categoryTension: "Art vs. commerce — the practice that has a point of view",
  },
  luxury: {
    label: "Luxury & Fashion",
    audiences: [
      "Ultra-High Net Worth Individuals",
      "Aspirational Luxury Consumers",
      "Fashion & Style Press",
      "Retail Buyers & Stockists",
      "Celebrity & Cultural Tastemakers",
      "Collectors & Connoisseurs",
      "Digital Luxury Consumers",
      "Global Flagship Visitors",
    ],
    competitors: [
      "LVMH portfolio brands",
      "Kering brands",
      "Independent luxury houses",
      "New-guard designer labels",
      "Emerging heritage brands",
      "Direct-to-consumer luxury",
    ],
    painPoints: [
      "Balancing digital accessibility with exclusivity perception",
      "Sustaining desirability while growing distribution",
      "Authenticity gaps between brand story and product reality",
      "Gen Z repositioning without alienating core UHNW base",
      "Marketplace saturation eroding perceived scarcity",
    ],
    readingSuggestions: [
      { title: "The Luxury Strategy", author: "Jean-Noël Kapferer", type: "Book" },
      { title: "Vogue Business", author: "Condé Nast", type: "Publication" },
      { title: "Business of Fashion", author: "BoF Media", type: "Publication" },
      { title: "Luxury: A Rich History", author: "Peter McNeil", type: "Book" },
    ],
    channelPriorities: [
      "Influencer",
      "PR & Media Relations",
      "Experiential / Events",
      "Social Media (Paid)",
    ],
    strategicThemes: [
      "Scarcity as strategy",
      "Culture as category",
      "The myth of origin",
    ],
    categoryTension: "Growth without dilution — scale that preserves mystique",
  },
  technology: {
    label: "Technology & SaaS",
    audiences: [
      "CTO & Technical Decision-Makers",
      "Product & Engineering Teams",
      "Enterprise Procurement",
      "Startup Founders",
      "Developer Communities",
      "Investors & VCs",
      "End Users (B2C)",
      "Channel Partners & Resellers",
    ],
    competitors: [
      "Established SaaS incumbents",
      "Venture-backed challengers",
      "Open-source alternatives",
      "Big tech platform products",
      "Niche vertical solutions",
      "In-house build advocates",
    ],
    painPoints: [
      "Explaining technical value in human terms",
      "Standing out in a noisy, funding-driven market",
      "Building trust without brand heritage",
      "Converting trial users into paying customers",
      "Retention and churn in competitive SaaS verticals",
    ],
    readingSuggestions: [
      { title: "Obviously Awesome", author: "April Dunford", type: "Book" },
      { title: "Crossing the Chasm", author: "Geoffrey Moore", type: "Book" },
      { title: "First Round Review", author: "First Round Capital", type: "Publication" },
      { title: "TechCrunch", author: "Verizon Media", type: "Publication" },
    ],
    channelPriorities: [
      "Content Marketing",
      "Search (SEO / SEM)",
      "Podcast / Audio",
      "Social Media (Paid)",
    ],
    strategicThemes: [
      "Category creation",
      "Community as moat",
      "Clarity as competitive advantage",
    ],
    categoryTension: "Feature parity vs. narrative — the brand that makes complexity simple",
  },
  finance: {
    label: "Finance & Professional Services",
    audiences: [
      "C-Suite & Board Level",
      "CFOs & Finance Directors",
      "Investment Committee Members",
      "Institutional Investors",
      "Regulatory Bodies",
      "High Net Worth Individuals",
      "SME Business Owners",
      "Media & Financial Press",
    ],
    competitors: [
      "Global investment banks",
      "Big Four consulting firms",
      "Boutique advisory practices",
      "Fintech disruptors",
      "Regional specialists",
      "Family office networks",
    ],
    painPoints: [
      "Building trust in a low-trust industry environment",
      "Communicating complex products to non-specialist audiences",
      "Regulatory constraints limiting brand expression",
      "Perceived homogeneity across peer firms",
      "Retaining talent through employer brand",
    ],
    readingSuggestions: [
      { title: "The Psychology of Money", author: "Morgan Housel", type: "Book" },
      { title: "Thinking, Fast and Slow", author: "Daniel Kahneman", type: "Book" },
      { title: "The Economist", author: "The Economist Group", type: "Publication" },
      { title: "Financial Times", author: "FT Media", type: "Publication" },
    ],
    channelPriorities: [
      "Content Marketing",
      "PR & Media Relations",
      "Email Marketing",
      "Podcast / Audio",
    ],
    strategicThemes: [
      "Trust as product",
      "Expertise made visible",
      "The long game narrative",
    ],
    categoryTension: "Credibility vs. approachability — authority without cold distance",
  },
  retail: {
    label: "Retail & Consumer",
    audiences: [
      "Everyday Consumers (B2C)",
      "Loyal Brand Advocates",
      "Price-Sensitive Shoppers",
      "Retail Media Buyers",
      "Wholesale & Distribution Partners",
      "Social Commerce Audiences",
      "Sustainability-Conscious Consumers",
      "Gen Z & Millennial Buyers",
    ],
    competitors: [
      "Category leaders (branded)",
      "Private label challengers",
      "D2C disruptors",
      "Marketplace sellers (Amazon / Etsy)",
      "International fast brands",
      "Premium independents",
    ],
    painPoints: [
      "Price pressure from platform and fast-brand competition",
      "Building loyalty in a deal-driven purchase environment",
      "Standing out on the digital shelf",
      "Supply chain transparency and sustainability expectations",
      "Declining physical retail footfall",
    ],
    readingSuggestions: [
      { title: "Contagious", author: "Jonah Berger", type: "Book" },
      { title: "The Brand Gap", author: "Marty Neumeier", type: "Book" },
      { title: "Retail Dive", author: "Industry Dive", type: "Publication" },
      { title: "Monocle", author: "Monocle Media", type: "Magazine" },
    ],
    channelPriorities: [
      "Social Media (Paid)",
      "Influencer",
      "Digital Display",
      "Email Marketing",
    ],
    strategicThemes: [
      "Identity purchase",
      "The store as theatre",
      "Product as manifesto",
    ],
    categoryTension: "Value vs. values — price point that does not cheapen the brand",
  },
  healthcare: {
    label: "Healthcare & Wellness",
    audiences: [
      "Patients & End Users",
      "Medical Professionals",
      "Health Insurance Buyers",
      "Hospital Procurement",
      "Public Health Bodies",
      "Wellness-Conscious Consumers",
      "Caregivers & Family Decision-Makers",
      "Investors & Biotech Partners",
    ],
    competitors: [
      "Established healthcare providers",
      "Digital health platforms",
      "Wellness consumer brands",
      "Public health service alternatives",
      "Pharmaceutical brands",
      "Prevention-focused startups",
    ],
    painPoints: [
      "Navigating strict regulatory communications frameworks",
      "Building emotional connection in a functional category",
      "Overcoming patient scepticism around new treatments",
      "Communicating clinical evidence without losing accessibility",
      "Differentiation in a trust-driven purchase environment",
    ],
    readingSuggestions: [
      { title: "Being Mortal", author: "Atul Gawande", type: "Book" },
      { title: "The Body", author: "Bill Bryson", type: "Book" },
      { title: "STAT News", author: "Boston Globe Media", type: "Publication" },
      { title: "Fierce Healthcare", author: "Fierce Media", type: "Publication" },
    ],
    channelPriorities: [
      "Content Marketing",
      "Email Marketing",
      "PR & Media Relations",
      "Social Media (Organic)",
    ],
    strategicThemes: [
      "Empathy as foundation",
      "Evidence-led storytelling",
      "Prevention over cure narrative",
    ],
    categoryTension: "Clinical credibility vs. human warmth — science that feels like care",
  },
  culture: {
    label: "Culture & Arts",
    audiences: [
      "Cultural Enthusiasts & Visitors",
      "Arts Funding Bodies",
      "Corporate Sponsors",
      "Educational Institutions",
      "Creative Communities",
      "International Cultural Tourists",
      "Press & Cultural Critics",
      "Policy & Government Commissioners",
    ],
    competitors: [
      "National institutions (Tate, V&A, etc.)",
      "Commercial galleries",
      "Festival organisers",
      "Digital cultural platforms",
      "International touring programmes",
      "Emerging artist collectives",
    ],
    painPoints: [
      "Funding uncertainty and over-reliance on public subsidy",
      "Communicating relevance to non-traditional audiences",
      "Low earned income relative to overhead costs",
      "Difficulty measuring cultural impact for funders",
      "Reaching younger and more diverse audiences",
    ],
    readingSuggestions: [
      { title: "The Art Newspaper", author: "The Art Newspaper", type: "Publication" },
      { title: "Art Monthly", author: "Art Monthly Publications", type: "Magazine" },
      { title: "Culture Track", author: "LaPlaca Cohen", type: "Report" },
      { title: "Museums & Society", author: "University of Leicester", type: "Journal" },
    ],
    channelPriorities: [
      "PR & Media Relations",
      "Email Marketing",
      "Content Marketing",
      "Experiential / Events",
    ],
    strategicThemes: [
      "Access as brand position",
      "The living institution",
      "Community as collection",
    ],
    categoryTension: "Preservation vs. provocation — the institution that challenges what it protects",
  },
  nonprofit: {
    label: "Non-profit & Social Impact",
    audiences: [
      "Individual Donors",
      "Corporate CSR Partners",
      "Grant-Making Foundations",
      "Beneficiaries & Communities",
      "Government & Policy Stakeholders",
      "Volunteers & Ambassadors",
      "Media & Advocacy Networks",
      "Board Members & Trustees",
    ],
    competitors: [
      "Sector-peer charities",
      "Corporate social responsibility programmes",
      "Government service providers",
      "Social enterprise competitors",
      "International NGO programmes",
    ],
    painPoints: [
      "Donor fatigue and cause competition for share of wallet",
      "Communicating impact credibly without oversimplification",
      "Brand inconsistency across fundraising and programme teams",
      "Retaining donor relationships beyond one-off campaigns",
      "Balancing emotional appeal with evidence of impact",
    ],
    readingSuggestions: [
      { title: "Doing Good Better", author: "William MacAskill", type: "Book" },
      { title: "Poor Economics", author: "Banerjee & Duflo", type: "Book" },
      { title: "Stanford Social Innovation Review", author: "Stanford University", type: "Publication" },
      { title: "The Nonprofit Quarterly", author: "NPQ", type: "Publication" },
    ],
    channelPriorities: [
      "Email Marketing",
      "Social Media (Organic)",
      "PR & Media Relations",
      "Content Marketing",
    ],
    strategicThemes: [
      "Impact as brand proof",
      "Radical transparency",
      "The movement model",
    ],
    categoryTension: "Heart vs. head — emotion that earns trust, data that proves change",
  },
  other: {
    label: "Other",
    audiences: [
      "Senior Decision-Makers (C-Suite)",
      "Brand Managers & Marketers",
      "End Consumers (B2C)",
      "Creative & Agency Partners",
      "Investors & Stakeholders",
      "Media & Press",
      "Industry Partners",
      "Internal Teams",
    ],
    competitors: [
      "WPP / Grey",
      "Ogilvy",
      "BBDO",
      "Leo Burnett",
      "Droga5",
      "72andSunny",
      "Wieden+Kennedy",
      "Anomaly",
    ],
    painPoints: [
      "Establishing differentiated brand positioning in a crowded market",
      "Aligning internal culture with external brand expression",
      "Building audience trust at speed",
      "Measuring brand equity alongside commercial outcomes",
    ],
    readingSuggestions: [
      { title: "Alchemy", author: "Rory Sutherland", type: "Book" },
      { title: "This Is Marketing", author: "Seth Godin", type: "Book" },
      { title: "Harvard Business Review", author: "Harvard Business Publishing", type: "Publication" },
      { title: "Monocle", author: "Monocle Media", type: "Magazine" },
    ],
    channelPriorities: [
      "Social Media (Organic)",
      "Content Marketing",
      "PR & Media Relations",
      "Email Marketing",
    ],
    strategicThemes: [
      "Clarity as differentiation",
      "Story before feature",
      "Brand as culture",
    ],
    categoryTension: "Visibility vs. meaning — presence that resonates beyond awareness",
  },
};

export const INDUSTRY_OPTIONS = [
  { value: "hospitality", label: "Hospitality & Food" },
  { value: "architecture", label: "Architecture & Design" },
  { value: "luxury", label: "Luxury & Fashion" },
  { value: "technology", label: "Technology & SaaS" },
  { value: "finance", label: "Finance & Professional Services" },
  { value: "retail", label: "Retail & Consumer" },
  { value: "healthcare", label: "Healthcare & Wellness" },
  { value: "culture", label: "Culture & Arts" },
  { value: "nonprofit", label: "Non-profit & Social Impact" },
  { value: "other", label: "Other" },
];
